### ISSUE TITLE
Prebuild Distributed Files

### ISSUE THREAD

**Issue by madnl** [Flipkart/ReactEssentials#31]
Currently the library seems to export the source files as they are, without transpiling ES6 or JSX syntax down to more vanilla JS. This forces users of the library to match the assumed babel configuration this library expects.

**Comment by naqvitalha** [comment]
The idea was that in IDEs such as Webstorm you can directly jump into well documented source code. Makes the flow easier. Also, react native does transpilation for packages by default. Using this on web is a different story though. Were you trying this on Web? We can maybe have a prebuilt version for web.

**Comment by madnl** [comment]
Yes, this came from trying the library on web

**Comment by naqvitalha** [comment]
This is done. Thanks for the feedback, we'd love to hear more if you do give this a try.
Ref: https://github.com/Flipkart/ReactEssentials/pull/32
