### ISSUE TITLE
Available Methods for navigating the list

### ISSUE THREAD

**Issue by ariona** [Flipkart/ReactEssentials#49]
There is no documentation on what available props and methods. 
Is there any method for navigating the list like `scrollTo`, `scrollToIndex`, `scrollToItem`
or a prop for setting initial list item to be focused?

**Comment by naqvitalha** [comment]
The documentation does mention support for initialRenderIndex or offset. All methods you mentioned are available too. It would be best to just go through props in code itself. It is well commented. Check this file https://github.com/Flipkart/ReactEssentials/blob/recyclerlistview-master/src/recyclerlistview/RecyclerListView.js

**Comment by ariona** [comment]
Thanks for pointing it out, i am a bit lost diving into the source code. but the code is well documented by the way.
You should update your `readme` file to include the available props and methods.

Thanks.

**Comment by naqvitalha** [comment]
Yeah, we'll try to do that soon. Thanks!
