### ISSUE TITLE
Force rerendering when data changes

### ISSUE THREAD

**Issue by AbdallaMohamed** [Flipkart/ReactEssentials#52]
I have a case where some data in my Redux store is being updated, and I want the RecyclerListView to update its rows. Currently, if the row has been rendered it's not updated until I scroll far away and then scroll back. Is there a method that I can call to imperatively rerender the visible rows?

**Comment by naqvitalha** [comment]
`rowHasChanged` passed to `DataProvider` is for the same purpose. Any issues there?

**Comment by AbdallaMohamed** [comment]
It doesn't run the render function of the row I'm afraid. And I've even changed the row has changed to use lodash's deep equality check, but with no luck.

**Comment by naqvitalha** [comment]
We've built multiple features where row data has changed and haven't any faced issues. This is basic functionality. Can you provide a quick repro on snack so that we can help you out?

**Comment by naqvitalha** [comment]
Reopen is issue still remains. As long as you have relevant checks in `rowHasChanged` this is a non issue.

**Comment by AbdallaMohamed** [comment]
I'll try to isolate the problem and let you know. Thanks for following up.

**Comment by naqvitalha** [comment]
Check `extendedState` props in v1.2.2.

**Comment by Timer00** [comment]
We had a pretty similar problem, the page would not update until you went further on the magazine and then came back.
By passing our state to extendedState the **problem was fixed**, now it re renders properly!
`extendedState={this.state}`

**Comment by samuely4ng** [comment]
> Check `extendedState` prop in v1.2.2.

thank you so much! I've been looking for this for a solid day

**Comment by sayo96** [comment]
None of the above solutions work for me.  
Here is my problem:
1. I use Recycler list for displaying a list of items (say 1,2,3,4,5)
2. When user deletes an item (say 1) i'm updating the dataProvider which is in local state. DataProvider in local state acts as the source for recycler list view
3. Even after the state changes the view remains the same. In my case even after the user deletes 1 and the latest values in state are (2,3,4,5) but the all the 5 items are still displayed.

The recycler list view has the correct changes (ie 2,3,4,5) when i navigate to a different section of the app and come back though. 

RowhasChanged /extended state solutions as suggested above don't work for me. Please help 🙏
