### ISSUE TITLE
Sticky header

### ISSUE THREAD

**Issue by sm2017** [Flipkart/ReactEssentials#66]
How can I have a sticky header like the following gif
![sticky header](http://blog.bafoly.com/wp-content/uploads/2015/10/stickylistview.gif)

**Comment by naqvitalha** [comment]
Same as https://github.com/Flipkart/ReactEssentials/issues/28. Not supported yet, but you can build it yourself.

**Comment by AbdallaMohamed** [comment]
@sm2017 Maybe you can try the solution in https://github.com/Flipkart/recyclerlistview/issues/72
